# \u0438\u043d-\u043c\u0435\u043c\u043e\u0440\u0438 \u041d2
spring.datasource.url=jdbc:h2:mem:mission_archive
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true