# \u043f\u043e\u0441\u0442\u0433\u0440\u0435\u0441
spring.datasource.url=jdbc:postgresql://localhost:5432/mission_archive
spring.datasource.username=postgres
spring.datasource.password=242368
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl